In [ ]:
# pytorch 是Facebook推出的一款深度学习框架，通过动态编译极大减轻了开发者的工作量，方便快速开发实现模型。
# 本部分为个人pytorch练习，把握其内在机制和实现细节

In [223]:
# 构建第一个神经网络来学习一个固定的函数，神经网络具有强大的拟合能力。
# [128,32] + ReLU + [32,8] +  ReLU + [8, 1] + Sigmoid

import numpy as np

# 目标函数
def func(x):
    return sum([x[:,i]/float(2*i+2) for i in range(x.shape[1])])

# print(func(np.random.rand(3,4)))

# 模型
import torch
# print(dir(torch.nn))
from torch.nn import Linear, ReLU, Sequential, Sigmoid
NET = Sequential(
#     Linear(128,32),
#     ReLU(),
#     Linear(32,8),
#     ReLU(),
    Linear(8,1),
    Sigmoid())

# input = torch.randn((10,128))
# print(input)
# print(NET(input).squeeze().detach()) # .squeeze(), torch.squeeze()
# print(torch.squeeze(NET(input)).detach()) # .squeeze(), torch.squeeze()

# 优化
from torch.optim import Adam, SGD
optimizer = SGD(NET.parameters(), lr=0.001,momentum=0.1) # 冲量系数
# optimizer = Adam(NET.parameters(), lr=0.001)
# criterion = torch.nn.MSELoss()
# criterion = torch.nn.L1Loss()
criterion = torch.nn.SmoothL1Loss()
for step in range(1000):
    optimizer.zero_grad() # 梯度置0
    # 输入数据
    input = torch.randn((10,8))
    # 生成标签
    label = func(input.detach())
    # 模型输出
    output = NET(input).squeeze()
    # 平方损失
#     loss = torch.sum((label-output)**2)
    loss = criterion(output, torch.tensor(label))
    # 优化
    loss.backward() # 梯度反向计算
    optimizer.step() # 梯度更新
    if step%100==0:
        print('第{}次迭代损失={}'.format(step, loss))

/Users/fubin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:46: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


第0次迭代损失=0.15837982296943665
第100次迭代损失=0.5138764381408691
第200次迭代损失=0.2319364994764328
第300次迭代损失=0.09167849272489548
第400次迭代损失=0.27909207344055176
第500次迭代损失=0.4107387959957123
第600次迭代损失=0.19654621183872223
第700次迭代损失=0.377009779214859
第800次迭代损失=0.31133395433425903
第900次迭代损失=0.1997448354959488


In [142]:
# 张量及其属性和用法

import numpy as np
import torch
data = torch.rand((1,2))
print('data:', data)
# 属性
print('.size():', data.size())
print('.dim():', data.dim())
print('.numel():', data.numel()) # number of elements
print('.dtype:', data.dtype)
# 创建张量
# 传入数据
print(torch.tensor(np.random.rand(1,2)))
# 0
print(torch.zeros((2,1)))
print(torch.zeros_like(data))
# 1
print(torch.ones((2,1)))
print(torch.ones_like(data))
# 指定值
print(torch.full((2,1), 78))
print(torch.full_like(data, 87))
# 对角
print(torch.eye(2))
# 空(未初始化)
print(torch.empty(2))
print(torch.empty_like(data))
# 等差数列
print(torch.range(1,4, step=1)) # [start, end]
print(torch.range(0,1, step=0.2)) # [start, end]
print(torch.arange(1,4, step=1)) # [start, end)
print(torch.linspace(0,10, steps=4)) # start, end, steps:  delta=(end-start)/steps
# 等比数列
print(torch.logspace(0,5, steps=10)) # start, end, steps:  delta=(10^end-10^start)/steps
# 随机生成： 标准均匀分布
print(torch.rand(4))
print(torch.rand_like(data))
# 随机生成： 标准正态分布
print(torch.randn(2))
print(torch.randn_like(data))
print(torch.normal(data))
# 随机生成： 指定正态分布（对应位置）
mean, std = torch.tensor([0.,4.]), torch.tensor([1.,10.])
print('normal:', torch.normal(mean, std))
# 随机生成： 离散均匀分布
print(torch.randint(0,3, (2,3))) # low, high, size
print(torch.randint_like(data, 10, 20)) # data, low, high
# 两点伯努利分布(概率为0值的概率)
print(torch.bernoulli(data))
# 多个两点分布
# 权重，n_samples取样次数
print(torch.multinomial(data, 2))
# 二维张量则返回二维张量，即每一行都取了n_samples次

# 随机排列
print(torch.randperm(5))

# 变形
print('.reshape(*):', data.reshape(2,1).shape)
print('torch.reshape:', torch.reshape(data, (2,1)).shape)
print('.reshape(-1):', data.reshape(-1).shape) # 打平
# 压缩维度长度为1
print('squeeze:', data.squeeze(dim=0).shape)
# 扩张一个维度，为1
print('unsqueeze:', data.unsqueeze(dim=-1).shape)
# 转置两个维度
print('transpose:', data.transpose(0,1).shape)
print('transpose:', data.t().shape) # 直接转置
# 指定各维度的顺序
print('permute:', data.permute(1,0).shape)


data: tensor([[0.4321, 0.6524]])
.size(): torch.Size([1, 2])
.dim(): 2
.numel(): 2
.dtype: torch.float32
tensor([[0.7703, 0.2616]], dtype=torch.float64)
tensor([[0.],
        [0.]])
tensor([[0., 0.]])
tensor([[1.],
        [1.]])
tensor([[1., 1.]])
tensor([[78],
        [78]])
tensor([[87., 87.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([0., 0.])
tensor([[2.3495e+35, 2.0005e+00]])
tensor([1., 2., 3., 4.])
tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000])
tensor([1, 2, 3])
tensor([ 0.0000,  3.3333,  6.6667, 10.0000])
tensor([1.0000e+00, 3.5938e+00, 1.2915e+01, 4.6416e+01, 1.6681e+02, 5.9948e+02,
        2.1544e+03, 7.7426e+03, 2.7826e+04, 1.0000e+05])
tensor([0.0478, 0.4494, 0.0777, 0.8772])
tensor([[0.0969, 0.7815]])
tensor([ 0.3298, -0.1942])
tensor([[0.2169, 0.4921]])
tensor([[-0.3568, -0.2769]])
normal: tensor([ 0.9602, 11.1494])
tensor([[1, 0, 2],
        [0, 2, 0]])
tensor([[15., 16.]])
tensor([[1., 1.]])
tensor([[1, 0]])
tensor([2, 4, 3, 0, 1])
.reshape(*): torch.Size(

/Users/fubin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:30: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
/Users/fubin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:31: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).


In [153]:
# 张量的高级用法

import numpy as np
import torch
data = torch.rand((2,3))
print('data=', data)

# 选择部分元素: 某一维度，选择哪几个元素
print('index_select:', data.index_select(1, torch.tensor([0,2])))
print(':', data[:,1:2]) # 连续选择
# 选择对应位置元素并返回一维张量
print('masked_select:', data.masked_select(torch.tensor([[0,1,0],[1,0,1]], dtype=torch.uint8))) # 同维度对应，类似.reshape(-1)
print('take:', data.take(torch.tensor([1,2,4]))) # .reshape(-1)后，按照下标检索
# 拼接
print('cat:', torch.cat([data, data], 0))
print('stack:', torch.stack([data, data], 2).shape) # 新增一维度来拼接
# 重复: 对应维度扩张倍数
print('repeat:', data.repeat([2,2]).shape)
# 

data= tensor([[0.4666, 0.0856, 0.0436],
        [0.4339, 0.0489, 0.8822]])
index_select: tensor([[0.4666, 0.0436],
        [0.4339, 0.8822]])
: tensor([[0.0856],
        [0.0489]])
masked_select: tensor([0.0856, 0.4339, 0.8822])
take: tensor([0.0856, 0.0436, 0.0489])
cat: tensor([[0.4666, 0.0856, 0.0436],
        [0.4339, 0.0489, 0.8822],
        [0.4666, 0.0856, 0.0436],
        [0.4339, 0.0489, 0.8822]])
stack: torch.Size([2, 3, 2])
repeat: torch.Size([4, 6])


/Users/fubin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:1356.)
  if sys.path[0] == '':


In [227]:
# 张量的计算

import numpy as np
import torch
data = torch.rand((2,3))
print('data=', data)

# 基本运算符号：+, -, *, /, **

# 倒数，开方，先开方后倒数
print('reciprocal:', data.reciprocal())
print('sqrt:', data.sqrt())
print('rsqrt:', data.rsqrt())
# 幂函数，指数, sigmoid，对数函数
print('pow', data.pow(2)) # x^2
print('exp:', data.exp()) # e^x
print('expm1:', data.expm1()) # e^x - 1
print('sigmoid:', data.sigmoid()) # 1/(1+e^x)
print('logit:', data.logit()) # 1/(1+e^(-x))
print('log:', data.log()) # 自然底数
print('log2:', data.log2()) # 底数为2
print('log10:', data.log10()) # 底数为10
print('log1p:', data.log1p()) # ln(1+x)
# 三角函数
print('sin:', data.sin())
print('asin:', data.asin())
print('cos:', data.cos())
print('acos:', data.acos())
print('tanh:', data.tanh())
print('atanh:', data.atanh())
print('sinh:', data.sinh())
print('cosh:', data.cosh())

# 符号函数: 1为正数,-1为负
print('sign:', (-data).sign())
# 绝对值
print('abs:', (-data).abs())
# 下整数，上整数，四舍五入，取整数部分，取小数部分
print('floor:', data.floor())
print('ceil:', data.ceil())
print('round', data.round())
print('trunc:', data.trunc())
print('frac:', data.frac())
# 除法: 余数
print('fmod:', torch.tensor(10).fmod(torch.tensor(3)))
print('remainder:', torch.tensor(10).remainder(torch.tensor(3)))
# 截断范围在某个范围内：限制范围
print('clamp:', data.clamp(0.2,0.6))

# 向量点积：仅限一维 同样大小，求和
print('dot:', data[:,0].dot(data[:,2]))
# 二维张量点积：
print('mm:', data.mm(data.t()))
# 二维张量和一维张量之间的点积: 最后一维相乘并求和
print('mv:', data.mv(data[1,:]))

# 矩阵求逆
print('inverse:', data.mm(data.t()).inverse())

# 复杂计算：求和约定，指定维度之间进行计算
print('einsum(ij,jk->jk):', torch.einsum('ij,jk->ik', data, data.t()))
print('einsum(ij,jk,km->im):', torch.einsum('ij,jk,km->im', data, data.t(), data))


data= tensor([[0.8797, 0.1840, 0.0028],
        [0.7228, 0.0723, 0.7652]])
reciprocal: tensor([[  1.1367,   5.4338, 353.4427],
        [  1.3836,  13.8256,   1.3069]])
sqrt: tensor([[0.9379, 0.4290, 0.0532],
        [0.8502, 0.2689, 0.8747]])
rsqrt: tensor([[ 1.0662,  2.3311, 18.8001],
        [ 1.1763,  3.7183,  1.1432]])
pow tensor([[7.7388e-01, 3.3868e-02, 8.0050e-06],
        [5.2238e-01, 5.2316e-03, 5.8551e-01]])
exp: tensor([[2.4102, 1.2021, 1.0028],
        [2.0601, 1.0750, 2.1494]])
expm1: tensor([[1.4102, 0.2021, 0.0028],
        [1.0601, 0.0750, 1.1494]])
sigmoid: tensor([[0.7068, 0.5459, 0.5007],
        [0.6732, 0.5181, 0.6825]])
logit: tensor([[ 1.9896, -1.4893, -5.8649],
        [ 0.9582, -2.5514,  1.1813]])
log: tensor([[-0.1282, -1.6926, -5.8677],
        [-0.3247, -2.6265, -0.2676]])
log2: tensor([[-0.1849, -2.4420, -8.4653],
        [-0.4684, -3.7893, -0.3861]])
log10: tensor([[-0.0557, -0.7351, -2.5483],
        [-0.1410, -1.1407, -0.1162]])
log1p: tensor([[0.6311, 0

In [217]:
# 分布统计

import numpy as np
import torch
data = torch.rand((2,3))
print('data=', data)

# 均值，求和，标准差, 方差，最大，最小，中位数，范数，第k大，积
print('mean:', data.mean())
print('sum:', data.sum())
print('std:', data.std())
print('var:', data.var())
print('max:', data.max())
print('min:', data.min())
print('median:', data.median())
print('norm:', data.norm(1)) # 几范数
print('kthvalue:', data.kthvalue(2)) # 每行一个，返回位置
print('prod:', data.prod())

# 比较: >, <, >=, <=, ==, !=
print('==:', data == data) # 逐个元素比较
print('equal:', data.equal(data)) # 整体比较

# nonzero
print('nonzero:', data.nonzero()) # 返回位置元组的列表

# where
print('where:', data.where(data>torch.tensor(.2), torch.tensor(1.)))

# 计算圆周率: pi*r^2 / 4 = p, 欧几里得空间上面积度量视为的均匀分布。
samples = torch.rand(10000000,2) # r=1
dist = samples.norm(p=2,dim=1)
ratio = (dist<1).float().mean()
print(ratio*4)

data= tensor([[0.2568, 0.9482, 0.4265],
        [0.2140, 0.8346, 0.7309]])
mean: tensor(0.5685)
sum: tensor(3.4110)
std: tensor(0.3112)
var: tensor(0.0969)
max: tensor(0.9482)
min: tensor(0.2140)
median: tensor(0.4265)
norm: tensor(3.4110)
kthvalue: torch.return_types.kthvalue(
values=tensor([0.4265, 0.7309]),
indices=tensor([2, 2]))
prod: tensor(0.0136)
==: tensor([[True, True, True],
        [True, True, True]])
equal: True
nonzero: tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2]])
where: tensor([[0.2568, 0.9482, 0.4265],
        [0.2140, 0.8346, 0.7309]])
tensor(3.1415)


In [12]:
# 变量
import torch

x = torch.autograd.Variable(torch.ones(2,2), requires_grad=True)
print(x)
y=x.mean()
y.backward()
print(x.grad)
print(x.grad.data)
x.grad.data.zero_()
print(x.grad.data)
print(x.data)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# 数据集Dataset

from torch.utils.data import Dataset, DataLoader
# 继承Dataset后，实现__len__(self)和__getitem__(self, idx)两个函数

class NewDataset(Dataset):
    def __init__(self):
        pass
    def __len__(self):
        pass
    def __getitem__(self,idx):
        pass
        return img, label

newdataset = NewDataset()
    
# 数据集迭代读取器DataLoader，多线程读取，批量大小, shuffle
dataloader = DataLoader(newdataset, batch_size=32, shuffle=True, num_workers=3)

for imags, labels in dataloader:
    pass



In [ ]:
# 训练

# 动态修改学习速率 lr_scheduler.StepLR
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9, weight_decay=0.1)
from torch.optim import lr_sheduler
# 按照训练步数改变：每step_size步为原来gamma
lr_sheduler = lr_sheduler.StepLR(optimizer, step_size=10, gamma=0.1)
# 按照指定步数改变：乘以gamma
multi_lr_sheduler = lr_sheduler.MultiStepLR(optimizer, milestones=[10,100], gamma=0.1)
# 每步乘以gamma
exp_lr_sheduler = lr_sheduler.ExponentialLR(optimizer, gamma=0.1)
# 按照特定指标变化修改
reduce_lr_sheduler = lr_sheduler.ReduceLROnPlateau(optmizer, 'min')
reduce_lr_sheduler(validate_loss)


# 模型保存与加载
msd = model.state_dict()
model.train(True)
model.train(False)  
model.load_state_dict(msd)


# 过拟合根本原因是：数据量 和 模型容量 之间不匹配
# 策略1: 数据量增加，行数、特征或知识，方式包括多任务正则学习和预训练等
# 策略2: 模型容量降低，包括正则项、dropout、设计容量低模型、学习率
